### ISSUE TITLE
Training from scratch

### ISSUE THREAD

**Issue by logicwong** [google-research/pix2seq#3]
Thanks for your awesome work! I want to reproduce the results in Table 1. When will you release the command for training model from scratch? Looking forward to your reply.

**Comment by chentingpc** [comment]
Hi, training from scratch was done in a legacy codebase which is more complicated than the current one, for which reason we do not plan to release. Furthermore, training from scratch follows the DETR setup with 1333 image size, which is very slow to train (1+ day for 300 epochs on 128 TPUs with ResNet-50 backbone, DC5 ones are several times slower). So it is actually faster to pretrain on Objects365 (or possibly other big detection datasets) with smaller image sizes (e.g. 640, or even 480) and fine-tune on COCO (e.g. for 20-60 epochs) with a larger image size (with our current codebase, we simply set a bigger image size without any change to the positional embedding for fine-tuning). That said, we did try to train our model with a ResNet-50 backbone from scratch in this codebase, and you can find the config [here](https://gist.github.com/chentingpc/18baf393d7b109225bdd531a7650a93a), it should get ~42 AP in 300 epochs (please note that due to some small architectural changes and possibly other details, this is ~1 AP worse than our legacy code).

**Comment by logicwong** [comment]
Thank you very much for the response! Your work is very helpful to my research, I will study your code to further improve my work.
